export const CHAT_LOADING_WORDS = [
  // Culinary
  'Baking',
  'Brewing',
  'Caramelizing',
  'Cooking',
  'Fermenting',
  'Flambeing',
  'Frosting',
  'Garnishing',
  'Julienning',
  'Kneading',
  'Leavening',
  'Marinating',
  'Proofing',
  'Sauteing',
  'Seasoning',
  'Simmering',
  'Stewing',
  'Tempering',
  'Whisking',
  'Zesting',
  // Kinetic
  'Cascading',
  'Frolicking',
  'Gallivanting',
  'Galloping',
  'Moonwalking',
  'Scampering',
  'Scurrying',
  'Shimmying',
  'Skedaddling',
  'Waddling',
  // Cerebral
  'Cerebrating',
  'Cogitating',
  'Contemplating',
  'Deliberating',
  'Musing',
  'Philosophising',
  'Pondering',
  'Ruminating',
  // Whimsical
  'Booping',
  'Canoodling',
  'Dilly-dallying',
  'Flibbertigibbeting',
  'Lollygagging',
  'Razzle-dazzling',
  'Shenaniganing',
  'Tomfoolering',
  'Topsy-turvying',
  'Whatchamacalliting',
  // Scientific
  'Crystallizing',
  'Ionizing',
  'Nebulizing',
  'Nucleating',
  'Osmosing',
  'Photosynthesizing',
  'Precipitating',
  'Sublimating',
  // Musical
  "Beboppin'",
  'Grooving',
  'Harmonizing',
  'Improvising',
  'Jitterbugging',
  'Jiving',
  'Sock-hopping',
  // Existential
  'Discombobulating',
  'Flummoxing',
  'Befuddling',
  'Combobulating',
  'Recombobulating',
];

/** How long each word stays visible before cycling */
export const CHAT_LOADING_WORD_ROTATE_MS = 4000;
