"""
LLM-as-Judge Evaluation: Compare Base vs Fine-tuned Model
Uses Gemini API to score model outputs on multiple criteria
"""

import os
import json
import torch
from pathlib import Path
from datetime import datetime
from typing import Dict, List
import google.generativeai as genai
from dotenv import load_dotenv
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import time

# ============== CONFIGURATION ==============

BASE_MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"
FINETUNED_MODEL_PATH = Path("models/qwen2-marketing-lora")

# Gemini configuration - Add your API key(s) here
GEMINI_MODEL = "gemini-2.5-flash"  # Updated to correct model name
GEMINI_API_KEYS = [
    "ADD-YOUR-GEMINI-API-KEY-HERE",
]

# Generation parameters
MAX_NEW_TOKENS = 200
TEMPERATURE = 0.7
TOP_P = 0.9
REPETITION_PENALTY = 1.1

# Evaluation criteria
EVALUATION_CRITERIA = {
    "relevance": "How well does the output address the given prompt? (1-10)",
    "cultural_appropriateness": "How culturally appropriate is the content for Pakistani/Eastern fashion? (1-10)",
    "creativity": "How creative, engaging, and original is the content? (1-10)",
    "language_quality": "Grammar, fluency, and professional language quality? (1-10)",
    "marketing_effectiveness": "How effective is this as marketing content? Persuasive, compelling? (1-10)"
}

# Test prompts
TEST_PROMPTS = [
    {
        "title": "Instagram Caption - Embroidered Shawl",
        "instruction": "Write an engaging Instagram caption for a luxury embroidered khaddar shawl from our winter collection."
    },
    {
        "title": "Product Description - Formal Suit",
        "instruction": "Create a compelling product description for a premium 3-piece velvet formal suit in royal blue."
    },
    {
        "title": "Email Marketing - Sale Announcement",
        "instruction": "Write a promotional email subject line and opening paragraph for a 30% off sale on our lawn collection."
    },
    {
        "title": "Social Media - Brand Story",
        "instruction": "Write a short brand story post highlighting our commitment to traditional Pakistani craftsmanship."
    },
    {
        "title": "Product Tagline - Summer Collection",
        "instruction": "Create a catchy tagline for our new summer lawn collection featuring floral prints."
    },
    {
        "title": "Instagram Story - New Arrival",
        "instruction": "Write engaging text for an Instagram story announcing the arrival of our festive kurta collection."
    },
]

# ============== HELPER FUNCTIONS ==============

class GeminiJudge:
    """LLM Judge using Gemini API"""
    
    def __init__(self, api_keys: List[str]):
        if not api_keys:
            raise ValueError("No Gemini API keys found. Please set GEMINI_API_KEY_1 in .env file")
        
        self.api_keys = api_keys
        self.current_key_index = 0
        self._configure_api()
    
    def _configure_api(self):
        """Configure Gemini API with current key"""
        genai.configure(api_key=self.api_keys[self.current_key_index])
        self.model = genai.GenerativeModel(GEMINI_MODEL)
    
    def _rotate_key(self):
        """Rotate to next API key if available"""
        if len(self.api_keys) > 1:
            self.current_key_index = (self.current_key_index + 1) % len(self.api_keys)
            self._configure_api()
            print(f"Rotated to API key {self.current_key_index + 1}")
    
    def evaluate_output(self, prompt: str, output: str, model_name: str) -> Dict:
        """
        Evaluate a single output using Gemini
        Returns scores for each criterion
        """
        evaluation_prompt = f"""You are an expert evaluator for marketing content, specifically for Pakistani and Eastern fashion brands.

TASK: Evaluate the following marketing content generated by an AI model.

PROMPT GIVEN TO MODEL:
{prompt}

MODEL OUTPUT:
{output}

EVALUATION CRITERIA:
Rate the output on each of the following criteria on a scale of 1-10:

1. RELEVANCE ({EVALUATION_CRITERIA['relevance']})
2. CULTURAL APPROPRIATENESS ({EVALUATION_CRITERIA['cultural_appropriateness']})
3. CREATIVITY ({EVALUATION_CRITERIA['creativity']})
4. LANGUAGE QUALITY ({EVALUATION_CRITERIA['language_quality']})
5. MARKETING EFFECTIVENESS ({EVALUATION_CRITERIA['marketing_effectiveness']})

INSTRUCTIONS:
- Provide a score (1-10) for each criterion
- Provide a brief justification (1-2 sentences) for each score
- Be critical but fair
- Consider the Pakistani fashion market context

RESPONSE FORMAT (JSON):
{{
    "relevance": {{"score": X, "justification": "..."}},
    "cultural_appropriateness": {{"score": X, "justification": "..."}},
    "creativity": {{"score": X, "justification": "..."}},
    "language_quality": {{"score": X, "justification": "..."}},
    "marketing_effectiveness": {{"score": X, "justification": "..."}},
    "overall_score": X.X,
    "overall_feedback": "..."
}}

Respond ONLY with valid JSON, no additional text."""

        max_retries = 3
        for attempt in range(max_retries):
            try:
                response = self.model.generate_content(evaluation_prompt)
                
                # Extract JSON from response
                response_text = response.text.strip()
                
                # Try to find JSON in response
                if "```json" in response_text:
                    response_text = response_text.split("```json")[1].split("```")[0].strip()
                elif "```" in response_text:
                    response_text = response_text.split("```")[1].split("```")[0].strip()
                
                evaluation = json.loads(response_text)
                
                # Calculate overall score if not provided
                if "overall_score" not in evaluation:
                    scores = [evaluation[criterion]["score"] for criterion in EVALUATION_CRITERIA.keys()]
                    evaluation["overall_score"] = round(sum(scores) / len(scores), 2)
                
                return evaluation
                
            except json.JSONDecodeError as e:
                print(f"  ⚠️  JSON decode error (attempt {attempt + 1}/{max_retries}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(1)
                else:
                    print(f"  Raw response: {response_text[:200]}")
                    return self._default_evaluation(f"JSON parsing failed: {e}")
            
            except Exception as e:
                print(f"  ⚠️  API error (attempt {attempt + 1}/{max_retries}): {e}")
                if "quota" in str(e).lower() or "rate" in str(e).lower():
                    self._rotate_key()
                if attempt < max_retries - 1:
                    time.sleep(2)
                else:
                    return self._default_evaluation(f"API error: {e}")
        
        return self._default_evaluation("Max retries exceeded")
    
    def _default_evaluation(self, error_msg: str) -> Dict:
        """Return default evaluation on error"""
        return {
            criterion: {"score": 0, "justification": error_msg}
            for criterion in EVALUATION_CRITERIA.keys()
        } | {"overall_score": 0.0, "overall_feedback": error_msg}


def format_chat_prompt(instruction: str) -> str:
    """Format instruction into Qwen2 chat format"""
    system_prompt = """You are a professional marketing assistant specializing in Eastern and Pakistani fashion.
Generate creative, culturally relevant marketing content for clothing brands."""
    
    prompt = f"""<|im_start|>system
{system_prompt}<|im_end|>
<|im_start|>user
{instruction}<|im_end|>
<|im_start|>assistant
"""
    return prompt


def generate_response(model, tokenizer, prompt: str, device: str) -> str:
    """Generate response from model"""
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            temperature=TEMPERATURE,
            do_sample=True,
            top_p=TOP_P,
            pad_token_id=tokenizer.eos_token_id,
            repetition_penalty=REPETITION_PENALTY,
        )
    
    # Decode and extract assistant's response
    response = tokenizer.decode(outputs[0], skip_special_tokens=False)
    
    if "<|im_start|>assistant" in response:
        response = response.split("<|im_start|>assistant")[-1]
        if "<|im_end|>" in response:
            response = response.split("<|im_end|>")[0]
    
    return response.strip()


def print_evaluation_result(title: str, instruction: str, 
                           base_output: str, base_eval: Dict,
                           ft_output: str, ft_eval: Dict):
    """Print formatted evaluation comparison"""
    print("\n" + "="*80)
    print(f"TEST: {title}")
    print("="*80)
    print(f"\nPrompt: {instruction}\n")
    
    # Base model
    print("-" * 80)
    print("BASE MODEL")
    print("-" * 80)
    print(f"Output: {base_output}\n")
    print("Scores:")
    for criterion in EVALUATION_CRITERIA.keys():
        score = base_eval[criterion]["score"]
        print(f"  {criterion.replace('_', ' ').title()}: {score}/10")
    print(f"\n  OVERALL: {base_eval['overall_score']:.2f}/10")
    if base_eval.get('overall_feedback'):
        print(f"  Feedback: {base_eval['overall_feedback']}")
    
    # Fine-tuned model
    print("\n" + "-" * 80)
    print("FINE-TUNED MODEL")
    print("-" * 80)
    print(f"Output: {ft_output}\n")
    print("Scores:")
    for criterion in EVALUATION_CRITERIA.keys():
        score = ft_eval[criterion]["score"]
        improvement = score - base_eval[criterion]["score"]
        indicator = "📈" if improvement > 0 else "📉" if improvement < 0 else "➡️"
        print(f"  {criterion.replace('_', ' ').title()}: {score}/10 {indicator} ({improvement:+d})")
    print(f"\n  OVERALL: {ft_eval['overall_score']:.2f}/10", end="")
    overall_improvement = ft_eval['overall_score'] - base_eval['overall_score']
    indicator = "📈" if overall_improvement > 0 else "📉" if overall_improvement < 0 else "➡️"
    print(f" {indicator} ({overall_improvement:+.2f})")
    if ft_eval.get('overall_feedback'):
        print(f"  Feedback: {ft_eval['overall_feedback']}")


def main():
    print("="*80)
    print("LLM-AS-JUDGE EVALUATION: Base vs Fine-tuned Qwen2.5-0.5B")
    print("="*80)
    
    # Initialize Gemini judge
    print("\nInitializing Gemini judge...")
    try:
        judge = GeminiJudge(GEMINI_API_KEYS)
        print(f"✓ Gemini configured with {len(GEMINI_API_KEYS)} API key(s)")
    except Exception as e:
        print(f"❌ Failed to initialize Gemini: {e}")
        return
    
    # Check device
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"\nDevice: {device}")
    
    # Check fine-tuned model
    if not FINETUNED_MODEL_PATH.exists():
        print(f"\n❌ Fine-tuned model not found at: {FINETUNED_MODEL_PATH}")
        return
    
    # Load tokenizer
    print(f"\nLoading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_NAME, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"
    
    # Load base model
    print(f"Loading base model: {BASE_MODEL_NAME}")
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_NAME,
        torch_dtype=torch.float16 if device == "cuda" else torch.float32,
        device_map="auto" if device == "cuda" else None,
        trust_remote_code=True
    )
    base_model.eval()
    if device == "cpu":
        base_model = base_model.to(device)
    
    # Load fine-tuned model
    print(f"Loading fine-tuned model: {FINETUNED_MODEL_PATH}")
    finetuned_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_NAME,
        torch_dtype=torch.float16 if device == "cuda" else torch.float32,
        device_map="auto" if device == "cuda" else None,
        trust_remote_code=True
    )
    finetuned_model = PeftModel.from_pretrained(finetuned_model, str(FINETUNED_MODEL_PATH))
    finetuned_model.eval()
    if device == "cpu":
        finetuned_model = finetuned_model.to(device)
    
    print("\n" + "="*80)
    print(f"Evaluating {len(TEST_PROMPTS)} prompts...")
    print("="*80)
    
    # Store all results
    all_results = []
    
    # Process each test case
    for i, test_case in enumerate(TEST_PROMPTS, 1):
        print(f"\n[{i}/{len(TEST_PROMPTS)}] Processing: {test_case['title']}")
        
        prompt = format_chat_prompt(test_case['instruction'])
        
        # Generate outputs
        print("  Generating base model output...")
        base_output = generate_response(base_model, tokenizer, prompt, device)
        
        print("  Generating fine-tuned model output...")
        ft_output = generate_response(finetuned_model, tokenizer, prompt, device)
        
        # Evaluate outputs
        print("  Evaluating base model...")
        base_eval = judge.evaluate_output(test_case['instruction'], base_output, "Base Qwen2.5-0.5B")
        
        print("  Evaluating fine-tuned model...")
        ft_eval = judge.evaluate_output(test_case['instruction'], ft_output, "Fine-tuned Qwen2.5-0.5B")
        
        # Store results
        result = {
            'title': test_case['title'],
            'instruction': test_case['instruction'],
            'base_output': base_output,
            'base_evaluation': base_eval,
            'finetuned_output': ft_output,
            'finetuned_evaluation': ft_eval
        }
        all_results.append(result)
        
        # Print comparison
        print_evaluation_result(
            test_case['title'],
            test_case['instruction'],
            base_output,
            base_eval,
            ft_output,
            ft_eval
        )
        
        # Small delay between API calls
        time.sleep(1)
    
    # Calculate aggregate statistics
    print("\n" + "="*80)
    print("AGGREGATE STATISTICS")
    print("="*80)
    
    base_overall_scores = [r['base_evaluation']['overall_score'] for r in all_results]
    ft_overall_scores = [r['finetuned_evaluation']['overall_score'] for r in all_results]
    
    print(f"\nOverall Average Scores:")
    print(f"  Base Model: {sum(base_overall_scores)/len(base_overall_scores):.2f}/10")
    print(f"  Fine-tuned Model: {sum(ft_overall_scores)/len(ft_overall_scores):.2f}/10")
    improvement = (sum(ft_overall_scores) - sum(base_overall_scores)) / len(ft_overall_scores)
    print(f"  Improvement: {improvement:+.2f}")
    
    print(f"\nAverage Scores by Criterion:")
    for criterion in EVALUATION_CRITERIA.keys():
        base_scores = [r['base_evaluation'][criterion]['score'] for r in all_results]
        ft_scores = [r['finetuned_evaluation'][criterion]['score'] for r in all_results]
        base_avg = sum(base_scores) / len(base_scores)
        ft_avg = sum(ft_scores) / len(ft_scores)
        improvement = ft_avg - base_avg
        print(f"  {criterion.replace('_', ' ').title()}:")
        print(f"    Base: {base_avg:.2f}/10, Fine-tuned: {ft_avg:.2f}/10, Improvement: {improvement:+.2f}")
    
    # Save results to JSON
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = Path(f"evaluation_results/llm_judge_{timestamp}.json")
    output_file.parent.mkdir(exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump({
            'timestamp': timestamp,
            'configuration': {
                'base_model': BASE_MODEL_NAME,
                'finetuned_model': str(FINETUNED_MODEL_PATH),
                'judge_model': GEMINI_MODEL,
                'evaluation_criteria': EVALUATION_CRITERIA
            },
            'results': all_results,
            'aggregate_statistics': {
                'base_average': sum(base_overall_scores)/len(base_overall_scores),
                'finetuned_average': sum(ft_overall_scores)/len(ft_overall_scores),
                'improvement': improvement
            }
        }, f, indent=2, ensure_ascii=False)
    
    print(f"\n✓ Results saved to: {output_file}")
    print("\n" + "="*80)
    print("Evaluation complete!")
    print("="*80)


if __name__ == "__main__":
    main()
